### ISSUE TITLE
Persist data in browser

### ISSUE THREAD

**Issue by Trinityyi** [Trinityyi/boardeaux#6]
- [ ] Store data in IndexDB or localStorage
- [ ] Persist between sessions
- [ ] Allow _sync_ wth JSON store

**Comment by Chalarangelo** [comment]
An interesting alternative which might solve two issues at the same time would be the [Native File System API](https://web.dev/native-file-system/), which (as far as I understand it) allows access to local file system for the purposes of read-write operations, so we can persist data to a user's machine like that. We need to consider security vulnerabilities, if it will be available to all users (browser/OS support, if it can be blocked for some Enterprise users) etc.
